#include "Musician.h"

Musician::Musician() : (string instrument,)

Musician::Musician(std::string instrument, int experience) ...

std::string Musician::get_instrument()...

int Musician::get_experience() ...
